### ISSUE TITLE
mkdir: cannot create directory '/etc/services': File exists

### ISSUE THREAD

**Issue by ook** [cpuguy83/docker-nfs-server#17]
Using this docker-compose.yml:

```yml
docker-nfs:
 image: cpuguy83/nfs-server
 privileged: true
 volumes:
 - /exports
 command:
 - /exports
 - /etc/services:/etc/services
```

Then running `docker-compose up`

Produce:

```
Creating nfsserver_docker-nfs_1 ...
Creating nfsserver_docker-nfs_1 ... done
Attaching to nfsserver_docker-nfs_1
docker-nfs_1  | mkdir: cannot create directory '/etc/services': File exists
nfsserver_docker-nfs_1 exited with code 1
```

Same results on MacOSX (docker Server Version: 17.06.0-ce)
and linux (docker Server Version: 17.05.0-ce)

Please advice :)
